# Generated by Django 4.2.5 on 2023-09-30 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_courses_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.register'),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='courses',
            unique_together={('degree', 'university')},
        ),
        migrations.AlterUniqueTogether(
            name='register',
            unique_together={('name', 'email')},
        ),
    ]
