# Generated by Django 4.2.5 on 2023-09-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_courses_course_id_alter_register_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courses',
            unique_together=set(),
        ),
    ]
