# Generated by Django 4.2.5 on 2023-10-06 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_courses_course_id_alter_courses_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table=None,
        ),
    ]
